const langController = async (req, res) => {
  res.json({
    buy: req.t('buy'), 
    sell: req.t('sell'),
    animals: req.t('animals'),
    crops: req.t('crops'),
    buy_animal: req.t('buy_animal'),
    sell_animal: req.t('sell_animal'),
    buy_crop: req.t('buy_crop'),
    sell_crop: req.t('sell_crop'),
    profile: req.t('profile'),
    price: req.t('price'),
    location: req.t('location'),
    category: req.t('category'),
    breed: req.t('breed'),
    milk_capacity: req.t('milk_capacity'),
    litres: req.t('litres'),
    select_price: req.t('select_price'),
    pregnacy_status: req.t('pregnacy_status'),
    child_status: req.t('child_status'),
    pashu_age: req.t('pashu_age'),
    can_bargain: req.t('can_bargain'),
    lactation_period: req.t('lactation_period'),
    sell_pashu_using_whatsapp: req.t('sell_pashu_using_whatsapp'),
    logout: req.t('logout'),
    my_posts: req.t('my_posts'),
    saved_posts: req.t('saved_posts'),
    enter_mobile_number: req.t('enter_mobile_number'),
    get_otp: req.t('get_otp'),
    verify_otp: req.t('verify_otp'),
    otp_sent_check_phone: req.t('otp_sent_check_phone'),
    cows: req.t('cows'),
    cow: req.t('cow'),
    buffalos: req.t('buffalos'),
    buffalo: req.t('buffalo'),
    goats: req.t('goats'),
    goat: req.t('goat'),
    sheeps: req.t('sheeps'),
    sheep: req.t('sheep'),
    hens: req.t('hens'),
    hen: req.t('hen'),
    select_category: req.t('select_category'),
    select_breed: req.t('select_breed'),
    child_status: req.t('child_status'),
    notifications: req.t('notifications'),
    settings: req.t('settings'),
    yes: req.t('yes'),
    no: req.t('no'),
    details_page: req.t('details_page'),
    category_preview: req.t('category_preview'),
    play: req.t('play'),
    pause: req.t('pause'),
    save_post: req.t('save_post'),
    share_post: req.t('share_post'),
    km: req.t('KM'),
    call_seller: req.t('call_seller'),
    category_preview_page: req.t('category_preview_page'),
    all_categories: req.t('all_categories'),
    years: req.t('years'),
    months: req.t('months'),
    kilometers: req.t('kilometers'),
    age_of_pashu: req.t('age_of_pashu'),
    pregnancy: req.t('pregnancy'),
    login_with_mobile: req.t('login_with_mobile'),
    verify_otp: req.t('verify_otp'),
    otp_sent_check_phone: req.t('otp_sent_check_phone'),
    enter_mobile_number: req.t('enter_mobile_number'),
    send_otp_again: req.t('send_otp_again'),
    please_verify_your_otp: req.t('please_verify_your_otp'),

    // Cow breeds
    jersey: req.t('jersey'),
    holstein_friesian: req.t('holstein_friesian'),
    brown_swiss: req.t('brown_swiss'),
    red_dane: req.t('red_dane'),
    ayrshire: req.t('ayrshire'),
    guernsey: req.t('guernsey'),
    jersey_cross: req.t('jersey_cross'),
    holstein_friesian_cross: req.t('holstein_friesian_cross'),
    gir: req.t('gir'),
    sahiwal: req.t('sahiwal'),
    red_sindhi: req.t('red_sindhi'),
    kankrej: req.t('kankrej'),
    hariana: req.t('hariana'),
    ongole: req.t('ongole'),
    khillar: req.t('khillar'),
    deoni: req.t('deoni'),
    nagori: req.t('nagori'),

    // Buffalo breeds
    murrah: req.t('murrah'),
    surti: req.t('surti'),
    jaffrabadi: req.t('jaffrabadi'),
    bhadawari: req.t('bhadawari'),
    nili_ravi: req.t('nili_ravi'),
    mehsana: req.t('mehsana'),
    nagpuri: req.t('nagpuri'),
    toda: req.t('toda'),
    banni: req.t('banni'),
    pandharpuri: req.t('pandharpuri'),

    // Goat breeds
    tellicherry: req.t('tellicherry'),
    osmanabadi: req.t('osmanabadi'),
    sirohi: req.t('sirohi'),
    boer: req.t('boer'),
    kanni_aadu: req.t('kanni_aadu'),
    kodi_aadu: req.t('kodi_aadu'),
    jamunapari: req.t('jamunapari'),
    black_bengal: req.t('black_bengal'),

    // Sheep breeds
    madras_red: req.t('madras_red'),
    mandya: req.t('mandya'),
    mecheri: req.t('mecheri'),
    bellary: req.t('bellary'),
    nilgiri: req.t('nilgiri'),
    ramanadhapuram_white: req.t('ramanadhapuram_white'),
    vembur: req.t('vembur'),
    deccani: req.t('deccani'),
    nalgonda: req.t('nalgonda'),

    fill_pashu_data:req.t('fill_pashu_data'),
    years_old:req.t('years_old'),
    for_sale:req.t('for_sale'),
    belongs_to_breed:req.t('belongs_to_breed'),
    is_bargainable:req.t('is_bargainable'),
    is_present:req.t('is_present'),
    not_present:req.t('not_present'),
    can_play_bargain:req.t('can_play_bargain'),
    cannot_play_bargain:req.t('cannot_play_bargain'),
    sell_on_whatsapp:req.t('sell_on_whatsapp'),
    select:req.t('select'),
    got_pregnant:req.t('got_pregnant'),
    did_not_have_pregnant:req.t('did_not_have_pregnant'),
    farmer:req.t('farmer'),
    cancel:req.t('cancel'),
    are_you_sure_to_logout:req.t('are_you_sure_to_logout'),
    logging_out:req.t('logging_out'),
    no_posts_in_this_category:req.t('no_posts_in_this_category'),
    notifications_not_found:req.t('notifications_not_found'),
    did_not_found_posts_from_you:req.t('did_not_found_posts_from_you'),
    no_saved_posts:req.t('no_saved_posts'),
    call:req.t('call'),
    are_you_sure_to_call:req.t('are_you_sure_to_call'),
    posted_date:req.t('posted_date'),
    these_are_required:req.t('these_are_required'),
    select_atleast_one_picture:req.t('select_atleast_one_picture'),
    please_login_to_proceed:req.t('please_login_to_proceed'),
    login:req.t('login'),
    enter_password:req.t('enter_password'),
    login_to_view_profile:req.t('login_to_view_profile'),
    removed_from_saved_posts:req.t('removed_from_saved_posts'),
    post_got_saved:req.t('post_got_saved'),
    please_submit_all_details:req.t('please_submit_all_details'),
    camera:req.t('camera'),
    gallery:req.t('gallery'),
    upload_image:req.t('upload_image'),
    delete_post:req.t('delete_post'),
    are_you_sure_to_delete_post:req.t('are_you_sure_to_delete_post'),
    delete:req.t('delete'),
    post_deleted_successfully:req.t('post_deleted_successfully'),
    successful:req.t('successful'),
    pashu_details_submitted_successfully:req.t('pashu_details_submitted_successfully'),
    error:req.t('error'),
    Something_went_wrong_Please_try_again:req.t('Something_went_wrong_Please_try_again'),
    your_password_is_incorrect:req.t('your_password_is_incorrect'),
    give_feedback:req.t('give_feedback'),
    enter_your_name:req.t('enter_your_name'),
  });
};

module.exports = { langController };
